### PR TITLE
Adding b.revert()

### PR DESCRIPTION
**Pull request by trych**
This adds `b.revert()` as proposed and discussed in #133.

As a reminder: This is useful during the development stage of a script, if you don't want to reset a document manually each time before you run the script (`b.clear(b.doc())` would not work in many cases, as it does not clear new layers and colors etc.)

So while developing your script, it would simply look like this:

```js
// @includepath "~/Documents/;%USERPROFILE%Documents";
// @include "basiljs/basil.js";

function draw() {

  b.revert();
  
  // all code that you are developing here

}

b.go();
```
And this would work both for saved and unsaved documents.

I did some testing and figured out that it is actually much quicker to close the document without saving and re-opening it than use InDesign's actual `doc.revert()` method, so I went with that. Tested this both with empty documents and with larger documents.

This modifies some conditional checks as well, which I explain in #203.

Added tests for it, it passes all other tests as well.

Please review. 🔍 🐛 😎

### CODE REVIEW

**Comment by fabianmoronzirfas** [comment]
Cool thing. To things I noticed when trying it out

`b.revert()`  

Creates a new doc when no document is open.

Expected outcome:  

Doing nothing. Or warning the User that there is no document to work on.

When more then one document (unsaved) is open, the document is closed and not recreated. See the recording.   
revert


Expected outcome:

A new blank doc shoud be created.

**Comment by trych** [comment]
Hi Fabian, thanks for giving it a try.

> b.revert()
> Creates a new doc when no document is open.

Actually basil.js *always* creates a new document, when you run it, even if you run the empty basil.js template. So, at the moment when the script reaches `b.revert()` there is already a document open (and yes, this gets reverted then).

So, I don't think it's a problem (also since this does usually only happen, if you run the script for the first time during developing stage. After developing stage it makes more sense to take `b.revert()` out (except you need it to reset the document between exports etc.).

> When more then one document (unsaved) is open, the document is closed and not recreated. See the recording.

Ok, this is not expected indeed, I will investigate, thanks!

**Comment by trych** [comment]
> When more then one document (unsaved) is open, the document is closed and not recreated. See the recording.

Ok, this remaining issue should be fixed now. If there are no other issues, this could be merged.

**Comment by b-g** [comment]
@trych Many thanks + looks good! Merged!

**Pull request merged**
