### PR TITLE
Closes #76

### PR DESCRIPTION
**Pull request by GitBruno**
Check if swatch is indeed a colour.

### CODE REVIEW

**Comment by trych** [comment]
Hi GitBruno,
I don't quite understand your commit. The swatch issue that fixes the "real world script" was addressed and fixed in #76 already. I changed it to only search the documents `colors`, which is what it is supposed to do, according to the description of the method. Can you explain why your commit changes the behavior to work with swatches again? Is there any advantage?

Thanks! :)

**Comment by GitBruno** [comment]
Hi @trych I think you still need to merge the branch then, I just discovered that there was another instance of searching the swatches occurs. I like your solution so I have implemented it there as well. Cheers!

**Comment by b-g** [comment]
Hi @GitBruno, many thanks for the PR! But I merged #75 by @trych which makes your one PR redundant! Any cheers for looking into it! Best, Benedikt

**Comment by GitBruno** [comment]
Perfect!

**Pull request closed without merging**
