### PR TITLE
Csv functions

### PR DESCRIPTION
**Pull request by ffd8**
- replace `CSV.encode()`/`CSV.decode()` w/ `stringify`/`parse`
- added `saveCSV()` and `loadCSV()`
- removed `CSV.delimiter()` and embedded into above functions
- added test for CSV `parse` and `stringify`
- updated changelog

### CODE REVIEW

**Comment by trych** [comment]
Ah, sorry, everything is in the PR already, hadn't seen it. Looks good on first glance, I will try to find some time tomorrow to properly review this.

**Comment by ffd8** [comment]
@trych – any chance to give this a quick closer look? I already updated the CSV tutorial on dev website to reference these functions, since it's the future for them anyways. I've tested and so far so good – was mainly just renaming things and making two combo functions, `loadCSV()` + `saveCSV()`.

**Comment by ffd8** [comment]
Merging this function – since it's so minor.. really just symantic changes + adding the `loadCSV()` + `saveCSV()` to match our JSON functions. Want to have the API docs match the correct way this should work + already updated the tutorial on the website with reference to these. If there's anything wrong with implementation, can be addressed as a new issue.

**Comment by trych** [comment]
@ffd8 Sorry, I was not aware this was still waiting for me, thanks for merging it.

**Comment by ffd8** [comment]
@trych no prob – yeah was waiting just to have a 2nd opinion check on it, but was minor PR. Tested in class today and worked smoothly – only needed `loadCSV()` with and without a custom delimiter. Worked fine for both local and URL based. 😅

**Pull request merged**
