### PR TITLE
canvasMode(BLEED/MARGIN/FACING_BLEEDS/FACING_MARGINS) fix for bounds()

### PR DESCRIPTION
**Pull request by ffd8**
The bounds was ignoring our canvasMode() - a potential bug since a long time that was occasionally run into.

### CODE REVIEW

**Comment by fabianmoronzirfas** [comment]
What about this PR? Is it still valid? Should get a review

**Comment by fabianmoronzirfas** [comment]
@basiljs

**Comment by ffd8** [comment]
I believe @trych ended up null+voiding this request when he did an overhaul recently on bounds? (canvasMode is still broken in current develop branch). I think his branch still needs to be added.. so I leave it up to him if this should be merged or not.

**Comment by trych** [comment]
This is still valid, but needs some re-work, as we now have global private variables to keep track of the x and y origin (as determined by the currently set canvas mode and page). Will have a look at this soon.

**Comment by trych** [comment]
Ok, I implemented `currOriginX` and `currOriginY` into the function, so it is more reliable now. Note that this does not fix the issues described in #166 yet, fixing those will require a major rewrite of the function and can hopefully done some time in the future.

Will merge.

**Comment by ffd8** [comment]
We've discovered that `canvasMode(MARGIN)` (and `FACING_MARGINS`) still messes up the `bounds()`.
Luckily no problems with normal/facing BLEED or PAGES

 ```
canvasMode(MARGIN); // FACING_MARGINS

  var r = rect(0, 0, width, height);

  var bnds = bounds(r);
  
  fill(255, 0, 0);
  var r2 = rect(bnds.left, bnds.top, bnds.width, bnds.height);
```

**Pull request merged**
