### PR TITLE
New method b.gradient()

### LINKED ISSUE #77: b.gradient()
I think a `b.gradient()` method would be cool.

It could work like this:

`b.gradient(string) --> returns existing gradient`

`b.gradient(arrayOfColors) --> creates a new gradient with the colors equally spread over the array`

`b.gradient(color1, color2) --> creates a gradient between c1 and c2`

`b.gradient(arrayOfColors, arrayOfSwatchStopPositions) --> creates a gradient with the colors at the given positions`

All except the first option could have an optional name argument, although we would need to decide how to name the gradients.

Any thoughts?

Please flag as feature.

### PR DESCRIPTION
**Pull request by trych**
This adds a new method `b.gradient` to retrieve a gradient or create a new one. I'll paste the basil-style documentation for the method that I added, to explain how it works.

```JavaScript
/**
* Creates a new gradient and adds it to the document, or gets a gradient by name from the document.
* If two colors are given as the first two parameters, a gradient is created that blends between these two colors. If an array of colors is used
* as the first parameter, a gradient with the contained colors will be created. The colors will be distributed evenly. If additionally to this array
* a second array of gradient stop positions is given, the colors will be positioned at the given gradient stops. Possible gradient stop positions
* range from 0 to 100. All parameter options allow for an additional name parameter at the end to name the new gradient.
* If a string is used as the only parameter, the gradient with that name will be returned, if it exists in the document.
*
* @cat Color
* @method gradient
* @param  {Color|Array|String} c1 First color of the gradient. Alternatively: Array of colors/gradients or name of gradient to get.
* @param  {Color|Array|String} c2 Second color of the gradient. Alternatively: Array of gradient stop positions (if first parameter is an array of colors).
* @param  {String} [name] Optional name of the gradient.
* @return {Gradient} Found or new gradient
*/
```

Additionally this required to introduce the method `b.gradientType()` as well as the constants `b.LINEAR` and `b.RADIAL` to switch the gradient type. Default is LINEAR, which was added to the initial doc setup.

`b.fill()` was updated to work with the new method.

A commented example script `gradient.jsx` was added to demonstrate the method and its different parameter options:

```JavaScript
#includepath "~/Documents/;%USERPROFILE%Documents";
#include "basiljs/bundle/basil.js";

function draw() {
  b.clear(b.doc());

  var dist = b.height / 4;

  // create two colors
  var red = b.color(255, 0, 0);
  var blue = b.color(0, 0, 255);

  // create array with 10 random colors
  var randomColors = [];
  for (var i = 0; i < 10; i++) {
    randomColors.push( b.color(b.random(0,255), b.random(0, 255), b.random(0, 255)) );
  }

  // create array with 10 random numbers (0-100)
  var randomNumbers = [];
  for (var i = 0; i < 10; i++) {
    randomNumbers.push( b.random(0, 100) );
  }

  // draw rectangles and fill them with different types of gradients

  // grandient from color1 to color2 
  b.fill( b.gradient(red, blue, "RedBlueLinear") );
  b.rect(0, dist * 0, b.width, dist);

  // gradient from array of colors
  b.fill( b.gradient(randomColors, "RandomCol") );
  b.rect(0, dist * 1, b.width, dist);

  // gradient from same array of colors with random gradient stop positions
  b.fill( b.gradient(randomColors, randomNumbers, "RandomCol/Pos") );
  b.rect(0, dist * 2, b.width, dist);

  // radial gradient from color1 to color2
  b.gradientType( b.RADIAL );
  b.fill( b.gradient(red, blue, "RedBlueRadial") );
  b.rect(0, dist * 3, b.width, dist);
}

b.go();
```
This will result in a page like this:
bildschirmfoto 2016-07-31 um 01 48 37

It passes all the tests.
Please comment and review. This closes #77.

### CODE REVIEW

**Comment by b-g** [comment]
Wow + many thanks!! Will check once I'm back in office (next week) ... so long, B

**Comment by b-g** [comment]
Hi @trych,

Many thanks for this wonderful contribution! 👍!

Just reviewed it and find it great! There is just one detail which I'm not so fond of, the `b.gradientType()` get function. I would vote to remove it. I know, it could be handy ... but I think we should be very conservative when it come to introduce new "vocabulary", for various reasons (maintaining, questions, documentation) ... but mainly there aren't any get API state functions in processing e.g. there is no getCurrentFill(). Users have to keep track of the active color on their own. I think we should follow the same minimal approach. What do you think?

@ffd8 after removing/discussing `b.gradientType()` ... ready to merge!

**Comment by fabiantheblind** [comment]
Actually `b.gradienType()` is not a getter is a setter (correct me if I'm wrong). It sets the current gradientType. Which is comapreable to b.rectMode or strokeWeight. But it could be integrated into the b.gadient call as an optional argument.

**Comment by fabiantheblind** [comment]
iiik the last merge created an conflict.

**Comment by b-g** [comment]
Ops ... your are right, it's a setter ... just back from vacation :) 

But then I would vote for a function name with has 'mode' in it e.g. `b.gradientMode`

**Comment by fabiantheblind** [comment]
Yes mode sounds good

**Comment by trych** [comment]
Yes, I was not sure, if I should use `gradientMode` or `gradientType`, decided on type, since that's the official InDesign term. But I'm happy with mode, too, will prepare another PR which changes it to mode.

@fabiantheblind , I will look into the conflict and see if I can resolve it (my first conflict *gasp*), if not, I will probably ask for your help. ;)

**Comment by trych** [comment]
Oh and one more thing, there should probably also some testing for the new `b.gradient()` method included in the test suite's `color-tests.jsx`. I will just include this in the next PR, right? Or should I use a separate branch for that?

**Comment by b-g** [comment]
Tests are great and much appreciated, but not a must for every PR. (It should not prevent people from contributing) ... If you fancy writing one, you can simply include it in the current PR. Cheers!

**Comment by b-g** [comment]
Hi @trych, news? This is a cool new feature, would be great to get that soon into the active master! :)

**Comment by trych** [comment]
Hi @b-g, I have not forgotten about it, I was just super busy the past week and will be quite busy the next weeks. I will try to give it a go at the weekend, would be also happy to have this in, of course.

From the beginning of September I will be available again and then continue with my bug hunting and feature suggesting. ;)

**Comment by trych** [comment]
Hi @b-g, I just did a few commits which resolve the remaining issues with this PR:

- Resolved the merge conflict (and feeling like a git pro in doing so  :stuck_out_tongue_winking_eye: )
- Renamed `b.gradientType()` to `b.gradientMode()` globally
- Added testing of gradients to `test/color-tests.jsx`

Please review. :)

**Comment by b-g** [comment]
Hi @trych, many thanks again! Mega! merged! Have a nice weekend, B

**Pull request merged**
