### PR TITLE
found a TODO made it a `@todo`

### PR DESCRIPTION
**Pull request by fabianmoronzirfas**
minor change. Only for the beauty of the docs.  

bildschirmfoto 2017-05-13 um 20 57 46

## VS

bildschirmfoto 2017-05-13 um 20 58 22

(Did you know there is a user called `@todo`?)

### CODE REVIEW

**Comment by trych** [comment]
I think we should move the ToDos out of the docs altogether. I think as soon as we find a Todo we should create an issue here on GitHub. That's a way more advanced system to keep track of ToDos and the user does not get confused by a ToDo in the reference.

**Comment by fabianmoronzirfas** [comment]
Yes we should can we still merge this? So we don't need to search for \@todo and todo and TODO and TODOS?

**Comment by b-g** [comment]
@fabianmoronzirfas Thanks for spotting that one! This is really really old legacy stuff. Yes, lets remove any "todo" stuff in source code. + Merged.

**Comment by fabianmoronzirfas** [comment]
okidoki. I'll put it on my list.

**Pull request merged**
