### PR TITLE
point(), quad() and triangle()

### PR DESCRIPTION
**Pull request by trych**
In the effort to make basil.js more similar to p5.js and Processing, this adds the shape functions `point()`, `triangle()` and `quad()`, which should be all really self explanatory.

Additionally this allows for a three parameter input for `ellipse()` if the user wants to create a circle.

Will merge this right away.

### CODE REVIEW

**Comment by fabianmoronzirfas** [comment]
I think something like this won't work. 

```js
function setup(){
function pseudoPointClass (x, y){

this.display = function(){
  this.point = point(x, y);
  this.point.x = 10; // this is pseudo code
}
}
this.update(){
// something else here
}
var points = [];
for(var i = 0; i < 10; i++){
points.push(new pseudoPointClass(10, i*10));
}
// do some stuff
for(var i = 0; i < points.length; i ++){
stroke(i*10);
points[i].display();
points[i].update();
}
}
```

**Comment by trych** [comment]
@fabianmoronzirfas @ffd8 I am getting notification emails about posts from both of you, however I don't see these posts here on the site. Is this stuff that you posted but then deleted again? Or is there something wrong with my Github?

**Comment by trych** [comment]
@fabianmoronzirfas @ffd8 I am getting notification emails about posts from both of you, however I don't see these posts here on the site. Is this stuff that you posted but then deleted again? Or is there something wrong with my Github?

**Comment by ffd8** [comment]
there were weird problems commenting last night, as github had some [dataserver issues](https://status.github.com/messages). I left you a comment in the pull request of your `image()` update, that placing in textframe doesn't seem to be working and a comment on my PR for `background()`

**Pull request merged**
