### PR TITLE
getURL updates - params + Windows support

### PR DESCRIPTION
**Pull request by ffd8**
- added support for CURL optional params (mac only) when using `loadString()` / `loadStrings()` / `loadJSON()`, since some API's (reddit) require sending a `--user-agent` to make a unique request.
- added support for Windows to also load URLs in the above functions! This had been a sore point for PC users in classes/workshops – but tested this script a few times and seems to work fine.

### CODE REVIEW

**Comment by ffd8** [comment]
I'll try to find a student on Windows to test this.. but anyone on Windows to give it a try?
`println(loadString('https://official-joke-api.appspot.com/jokes/programming/random'));`

**Review by trych — CHANGES_REQUESTED** [review]
I think this curl functionality should be moved to a plugin, especially when it is Mac only, I also think it is too specific to be included in such a function. We can always use the `shellExecute()` function, if we need to get really specific with some shell commands.

With the download function on windows:
While I am happy that there is something working on Windows, I would much prefer to have the `shellExecute()` function itself work on Windows and then have the download functions rely on that internally instead of having a really specific download-only windows shell functionality within the download function.

I remember I started working on this a while back, but never finished it. Maybe what you have now in the download function could be used as a starting point to get the shell function in Windows working?

**Comment by ffd8** [comment]
Just a reminder– this isn't about the downloading of things (images etc) – just the grabbing of strings from remote location. Our current `getURL()` has always been using curl (and was always mac only) – this change opens up that functionality to Windows. The second modification is for pretty specific curl options like --user-agent. I don't think the curl should be a plugin – since it should be out of the box that one can pass a URL to `loadString()` etc.

While the `shellExecute()` could use some universal OS love, this should patch a problem that's existed for years.

**Comment by trych** [comment]
> Just a reminder– this isn't about the downloading of things (images etc) – just the grabbing of strings from remote location. Our current `getURL()` has always been using curl (and was always mac only) – this change opens up that functionality to Windows.

**Comment by trych** [comment]
Sorry, clicked the wrong button.

**Comment by trych** [comment]
> Just a reminder– this isn't about the downloading of things (images etc) – just the grabbing of strings from remote location. Our current `getURL()` has always been using curl (and was always mac only) – this change opens up that functionality to Windows.

Hm. Okay. While I still think this should internally use `shellExecute()`, there is no harm including that part for now to unlock the downloading for Windows users.

> The second modification is for pretty specific curl options like --user-agent.

Exactly, since these modifications are pretty specific, I would not want to include them in the general download functions. Those who need these specific options should be advanced enough to easily use the `shellExecute()` function and pass those parameters there.
And I am 100% against adding yet another Mac-only feature, as I was – quite the opposite – hoping to close this Mac-Windows gap in basil altogether soon.

If you insist of having some Mac-only functionality added somewhere, then it's not a problem to add it as a plugin.

**Comment by ffd8** [comment]
FYI – downloading (images) remains non-existant for Windows (can't work on that, as I'm Mac based). Nevertheless, this is just about scraping/pinging information from the internet – APIs, etc. and updating our existing functions for that. 

It's now changed to allow a custom user-agent for both Mac + Windows(!). Seems special, but I was surprised that it was necessary during a workshop recently when using Reddit's GET API (and student was a complete beginner – wouldn't be doing any `shellExecute()` themselves).

Reddit API call endpoint: 
`https://www.reddit.com/r/todayilearned/random.json`

Attempt to grab JSON data:
`var grabData = loadJSON("https://www.reddit.com/r/todayilearned/random.json");`
Fails with a warning of `Too Many Requests`.

In workshop, hacked our `loadJSON()` (doing ugly 's magic due to how getURL works):
`var grabData = loadJSON("https://www.reddit.com/r/todayilearned/random.json' --user-agent 'blahblahblah");`

With new update:
`var grabData = loadJSON("https://www.reddit.com/r/todayilearned/random.json', 'blah');`
= Success, returns JSON data since (for now) no user-agent is sending 'blah'

Tiny feature that may be more necessary if other APIs start clamping down who/what pings them. Looked through CURL options and this is the only one that I've run into needing. I want to make API calls as easy as possible, since that's a huge strength of basil.js

**Comment by trych** [comment]
Ok, gave your Reddit example a try and I agree, this is a helpful extension.

I can't really test this on Windows right now, but I assume you got it to work? If that's the case feel free to merge.

> FYI – downloading (images) remains non-existant for Windows

Yes, that one should be high on our priority list.

**Review by trych — APPROVED** [review]

**Comment by ffd8** [comment]
FYI – just ran into the user-agent issue again after finding and demo'ing the nice and simple [duckduckgo API](https://duckduckgo.com/api) – after 4 pings it stops working.. plug in a user-agent and ping away. 

And yes yes to download being high on list.. hopefully can find windows folks to help with the VBS for that. Will keep searching for examples...

**Comment by trych** [comment]
Yes, as I said above, if the user-agent thing works, please go ahead and merge. The reddit example demonstrated perfectly why it is helpful.

**Comment by ff6347** [comment]
Do you know this script? http://rorohiko.blogspot.com/2013/01/geturlsjsx.html It uses a different way to access data over http.

**Comment by ff6347** [comment]
hm only does http as far as I can see (not https).

**Pull request merged**
