### PR TITLE
starting linting

### PR DESCRIPTION
**Pull request by fabianmoronzirfas**
So i did some linting on the first file. `color.js`
Ran the tests and all are passing.  
I did not commit a build of the bundled version so we don't run into conflicts until PR #95 is merged.  

# Rules to consider

---  

[consistent-return - Rules - ESLint - Pluggable JavaScript linter](http://eslint.org/docs/rules/consistent-return)

States that functions should always return a value or never. Not some do some dont. Actually I think it would be good to go for a always return value. Could be:  

    return 0;

if nothing the users needs comes back. Currently functions without return statement return `undefined`.  

---  

[max-len - Rules - ESLint - Pluggable JavaScript linter](http://eslint.org/docs/rules/max-len)

Lines should not exeed a specific length.  

I'm not sure what happens with the comments for yuidoc. Anyone knows what happens with breaklines?  

if it doesn't create any problems I would say lets go for a max length of 80 or 100 characters. Lines stay more readable like this.  

---  

[no-lonely-if - Rules - ESLint - Pluggable JavaScript linter](http://eslint.org/docs/rules/no-lonely-if)  

> disallow if statements as the only statement in else blocks 

Example:  

Wrong

    if (condition) {
        // ...
    } else {
        if (anotherCondition) {
            // ...
        }
    }

Right:  

    if (condition) {
        // ...
    } else if (anotherCondition) {

    }

---  

[no-else-return - Rules - ESLint - Pluggable JavaScript linter](http://eslint.org/docs/rules/no-else-return)

Example 

[basil.js/color.js at master line 183](https://github.com/basiljs/basil.js/blob/master/src/includes/color.js#L183)  

Currently it is:  

    if (typeof a === "string") {
      newCol = findInCollectionByName(currentDoc().colors, a);
      if (newCol) {
        return newCol;
      } else {
        error("b.color(), a color with the provided name doesn't exist.");
      }

And it should be:  

    if (typeof a === "string") {
      newCol = findInCollectionByName(currentDoc().colors, a);
      if (newCol) {
        return newCol;
      } else if(newCol === null) {
        error("b.color(), a color with the provided name doesn't exist.");
      }

The some goes for [basil.js/color.js at master line 329](https://github.com/basiljs/basil.js/blob/master/src/includes/color.js#L329)  
The some goes for [basil.js/color.js at master line 513](https://github.com/basiljs/basil.js/blob/master/src/includes/color.js#L513)  

---  

I currently set these rules to warn instead of error. I will provide a write up on how to configure sublime and eslint to have a proper environment.

### CODE REVIEW

**Comment by trych** [comment]
> Could be: `return 0;`

Is returning `0` not problematic in cases, where `0` can be a valid output (and for example `null` wouldn't be. I.e. would it not be better to always return `null` instead? Or am I misunderstanding something?

And I don't quite understand the last point. Does the error count as a return statement here?
And should it then not rather be

```JavaScript
if (typeof a === "string") {
  newCol = findInCollectionByName(currentDoc().colors, a);
  if (newCol) {
    return newCol;
  } 
  error("b.color(), a color with the provided name doesn't exist.");
```
after linting?

**Comment by fabianmoronzirfas** [comment]
## About consistent return values  

In languages like c++ it is normal to have a return value of 0 when everything went fine. If there was an error you return 1 or a error number. After reading the eslint docs I'm a bit confused myself. I think I got it wrong.  

Having a

    return null;

at the end of the function solves the lining error. I think the rule is not about every function has to have a return statement but rather about if there is a return statement, then each "endpoint" should have a return statement.  

Actually it makes sense that have that consistent. It allows to always check if the returned value is what we need or null.

**Comment by fabianmoronzirfas** [comment]
## About else return

In this case the snippet I provided is to short. We need to take a look at the whole function. The snippet just says

    if a is a string and I can find it in the collection return it if not warn the user. 
The else is right in that case but the `else if` is more accurate. The function still goes on if it is not a string.

**Comment by fabianmoronzirfas** [comment]
We don't need to comply to all the rules eslint gives us. We can disable them. I actually like it to have the code a bit more verbose but easier to understand. These are a thing of style and also opinion.

**Comment by trych** [comment]
Aah, now this has been merged, before I could give a comment on the cleaned code.

Few points that come to mind:

1. Did we not decide on single quotes instead of double quotes. I seem to remember that.
2. What about [line 314](https://github.com/basiljs/basil.js/pull/104/files#diff-2993dce13ed8da7b77ce266e06a3bf90R314)? I guess it is commented out, since `props` is not used anywhere. I would strongly vote for taking it out altogether then. Else there will be lot of zombie code left and later we are not sure if it needs to stay there or not.
3. About the last rule mentioned above: I still do not understand the two different versions that you are comparing. Could you provide the whole snippet after linting? I think if there are rules that we do not really understand or whose benefit we don't really understand, we should actually *not* turn them on.

**Comment by fabianmoronzirfas** [comment]
@trych 
About quotes:  

I remember having already a discussion about that. @b-g and I where for single quotes @ludzeller made the point that Processing uses double quotes so porting code from Processing would be easier.  

here #34 and here #33  

About l314 props:

Yes you are right. I forgot about it. Sorry. I will include it in the next PR.  

About rules we don't understand and:  

Of course rules that we don't consider important for us should not be in there. I will take a deeper look into it and report back.  

@basiljs woohoo! linting is happening. I ❤️  it.

**Comment by fabianmoronzirfas** [comment]
About this branch. I will use it to push more linting changes. So please don't delete it.

**Pull request merged**
