### PR TITLE
Solution for transformation issue #222

### PR DESCRIPTION
**Pull request by bohnacker**
This commit solves the problem, that rotate and scale behave
differently in InDesign and Processing. At least I hope so.

### CODE REVIEW

**Comment by trych** [comment]
Oooo, christmas is coming (1 week) early this year. @bohnacker thank you so much for looking into this, really appreciate that you help out with this stuff, that is over our (or at least my) heads.

I will give this some good testing later and report back, if this works for me.

**Comment by trych** [comment]
Ok, I had a closer look at this and it seems to work really, really nicely. Tested a lot of stuff and I am really impressed that with so few lines changed, suddenly everything seems to work!

As there was some stuff missing (matrix fixes for `b.text()`, `b.image()` and `b.duplicate()` as well as the bundling of the basil.js file), I moved your changes to a new [transformation branch](https://github.com/basiljs/basil.js/tree/transformation) to be able to work on all remaining changes.

Before this gets merged, I would actually like to implement the new `b.transform()` in the same branch, because the merge will break pretty much _all_ scripts that ever used `b.transform()` and `b.scale()`. By implementing `b.transform()` users will have a method at hand that works like the old "broken" transforms.

@basiljs What do you guys think? Sounds like a plan?

Thanks again @bohnacker for this great contribution!

**Comment by fabianmoronzirfas** [comment]
applause  

Thank you @bohnacker great work. @trych I think we can wait or merge this right away. It's up to you. I think your students might be the only ones using the develop branch for their work, so if you think that is a better way 👍

**Comment by b-g** [comment]
@bohnacker Yay! Super mega cool! 🙏👏🎄

**Comment by trych** [comment]
Closing this, so the remaining changes can be put in the transformations branch.

**Pull request closed without merging**
