### PR TITLE
basiljs gets points!

### PR DESCRIPTION
**Pull request by ffd8**
- 4 new point based functions: `createOutlines()`, `addPoints()`, `points()`, `pointsInPaths()`
- w/ initial research by @kajetansom on point getting and interpolating, extended to handle live type, multi-line type, pageitems, etc.
- `createOutlines()` built upon outline pseudocode from @fabianmoronzirfas on issue #100 

Some sample code for the new functions:

```js
  // create text and outline it
  textSize(100);
  var tf = createOutlines(text("basil.js", 50, 50, width, height));
  
  // add # of points between points of outline
  addPoints(tf, 5);
  
  // get all points as 1D array
  var pts = points(tf);
  
  // get all points in separate paths as 2D array
  var ptsPaths = pointsInPaths(tf);
  
  
  // redraw 1D array from points()
  tf.remove();
  noFill();
  beginShape();
  for (var i = 0; i < pts.length; i++) {
      vertex(pts[i].x, pts[i].y);
  }
  endShape();
  
  
  // redraw 2D array from pointsInPaths()
  //tf.remove();
  noFill();
  translate(0, 150);
  for (var j = 0; j < ptsPaths.length; j++) {
    beginShape(CLOSE);
    for (var i = 0; i < ptsPaths[j].length; i++) {
        vertex(ptsPaths[j][i].x, ptsPaths[j][i].y);
    }
    endShape();
  }


  // redraw wildstyle
  noFill();
  translate(0, 150);
  var offset = 15;
  for (var j = 0; j < ptsPaths.length; j++) {
    beginShape(CLOSE);
    for (var i = 0; i < ptsPaths[j].length-offset; i++) {
        vertex(ptsPaths[j][i+offset].x, ptsPaths[j][i+offset].y);
        vertex(ptsPaths[j][i].x, ptsPaths[j][i].y);
    }
    endShape();
  }
```
screen shot 2018-04-02 at 20 33 30

### CODE REVIEW

**Comment by fabianmoronzirfas** [comment]
Nice. I'm a bit behind on my reviews lately. Maybe @trych finds some time soonisher then me.

**Comment by trych** [comment]
Sweet! Can't make any promises, but will try to have a look at it soon!

**Comment by fabianmoronzirfas** [comment]
Did you see these conflicts? for math.js? 
Did you rebuild the basil.js file?

**Comment by trych** [comment]
> Try/Catch, what is the problem with them?

It's just not very clean coding and a bit like "let the user do their stuff and see what happens" instead of planning it carefully and do proper checking of inputs. And as it stands right now (without the native InDesign error message) it is even more confusing, because I might get a error message like `Be sure to use:\n Story | TextFrame | Paragraph | Line | Word | Character"` after passing a word, so that's confusing. Mixing this with a native error message is also not good, because then you might have different local languages mixed in one error message.

Instead I would – as it is done in most basil functions currently – carefully check by code for each condition that needs to be fulfilled to use the function. That means first check, if the correct type of object was passed. If not give a helpful basil error. This error should avoid most further errors right away. Then, if necessary, check if the object has a path (or whatever your function needs). If not, give a helpful basil message. And so on.

Right now there are quite a few ways to "break" the functions and get caught in the try/catch statement. If there is proper check of the inputs, that could be avoided. Does that explanation help? If not, let me know, I might find some time to put together an example for one of the functions.

> do I need to cancel this pull, or can I simply modify it?

I think the cleanest would be to actually cancel this PR and prepare a new one, else all these formatting changes back and forth would end up in the git history. Would that be okay for you?

**Comment by ffd8** [comment]
Closed! Replaced by a much better set of functions in #352 – integrating the helpful suggestions above. Tested it against so many scenarios.. should be quite safe now... and no try/catch!

**Pull request closed without merging**
