### PR TITLE
documentation node_module and api.json creation

### PR DESCRIPTION
**Pull request by fabianmoronzirfas**
This is just for creating the docs. No changes to the library introduced.

### CODE REVIEW

**Comment by b-g** [comment]
@fabianmoronzirfas
Wow, very cool! 

The docs generate with `npm run docs-html` look already very promising!

questions/comments:
* I guess it is on purpose that `npm run watch` also creates all the time `api.json`, may I ask why this makes sense?
* How could the old custom doc categories be transferred to the new docs worksflow. It seems grouping is possible e.g. `Vector` is a single list item in the left column.

**Comment by fabianmoronzirfas** [comment]
Sorry. I did not want to add this to the watch task. Just to the bundling (but the watch task uses bundling 🤔) .  

I actually don't wan't to use the generated HTML just the .json. See https://basiljs.github.io/ I'm trying to make sense of the generated JSON. It is quite large and has lot's of infos that we might not need.

**Comment by b-g** [comment]
Ok + Merged + Thanks!

The generated HTML would be fine fore me (if it comes with better categories/grouping) ... Do you really want to put so much effort into it, just for the sake of having it look more "basil website style" like?

**Comment by fabianmoronzirfas** [comment]
The problem I see is adding groups to the existing html layout will give me the same amount of headache as writing it myself from scratch. I already have [a way to extract the data we need](https://github.com/basiljs/basiljs.github.io/blob/master/.bin/json-transform.js) from the api.json. There are some parts currently still missing. For me it feels safer to write this using liquid then trying to transform it using some JS magic.

**Comment by fabianmoronzirfas** [comment]
Also. Yes. Some nice basil style will be there to 😉

**Comment by b-g** [comment]
Ok + Sure! Nobody will say no! :)

**Comment by trych** [comment]
I remember in the Skype call we decided to have it structured like the p5.js docs, which means one overview page with all functions and then a small sub-page for each single function. Are you still planning for this?

Would be nice, because especially documentation for stuff like `b.color()`, errr, `color()` will be quite detailed as it has many different options (compare the [p5.js color doc](http://p5js.org/reference/#/p5/color) for example).

**Comment by fabianmoronzirfas** [comment]
Could be done. I could generate sub pages from the data we have.  Should we take these conversations over into the pages repo?

**Pull request merged**
