### PR TITLE
adding couple week/day functions

### PR DESCRIPTION
**Pull request by ffd8**
- added `week()` for returning value of week throughout year
- added `weekdayCount()` for returning value of weekday
(ran into the need for these during a recent workshop)

### CODE REVIEW

**Review by trych — CHANGES_REQUESTED** [review]
Looks good overall, but regarding the weekday functionality:

I would prefer to just have a function to return the current weekday as a number, name that one `weekday()` and in turn get rid of the current `weekday()` function that returns the English weekday names. So basically, keep your two new functions and kick out the old one.

If we have a function to return the weekdays as numbers, then it's easy enough to write a quick array with names in whatever language you prefer which is much more flexible and much more in the spirit of Processing/p5/basil to be open to all (and not just English users).

What do you think?

Also, please add a quick note on the changes to the changelog.

**Comment by ffd8** [comment]
I agree the printed days of the week probably isn't necessary, especially since it's only English. But only returning numbers becomes a little strange... since JS for the day of the week returns 0 (Sunday) to 6 (Saturday)... based on ISO, should refer to numbers as 1 (Monday) and 7 (Sunday).. ha. Maybe it's best to leave it 0-6 (so it's cycles nicely through someone's custom array.. and if one wants the number like ISO, do some math to the output (like currently implemented)?

**Comment by trych** [comment]
> Maybe it's best to leave it 0-6

Yeah, even I as a German agree. I mean it's easy enough to just move my `"Sonntag"` string to the beginning of my array once I notice my days are off.

**Comment by ffd8** [comment]
Changes made - should be good.

**Review by trych — APPROVED** [review]

**Comment by trych** [comment]
Looks good, thanks!

**Pull request merged**
