### PR TITLE
selection() as setter

### PR DESCRIPTION
**Pull request by trych**
Allows to use `selection()` as setter as explained in #238 .
Will merge right away.

### CODE REVIEW

**Comment by ffd8** [comment]
Eek, I somehow hadn't used `selection()` since this change. But it killed the previous function of 'selection()' to grab whatever was selected within InDesign interface?? Make a textFrame or polygon within InDesign GUI, select it, then run:

```
var sel = selection();
inspect(sel);
```

Returns 'undefined is not an object'. 
It shouldn't require param, so that it can still be used to grab whatever pageItem was clicked on (we've used it for making scripts that you run from within InDesign, selecting something then presto chango to it).

**Comment by trych** [comment]
Yup. I did not want to change this behaviour of course, it was just a bug in the implementation. Fixed in the current develop branch (see #330).

**Comment by ffd8** [comment]
Thanks again for fixing the issue. 
Still curious how you're using it as described in #238 ..

**Comment by trych** [comment]
You mean how to use it as a setter?
You just give the object to be selected as an argument and then you could – for example – export a png and in the export setting set it to selection only, so only the selected part will be exported.

**Pull request merged**
