### PR TITLE
Bugfix #143 isNumber(), added tests

### PR DESCRIPTION
**Pull request by b-g**

### CODE REVIEW

**Comment by fabianmoronzirfas** [comment]
Whats that? Did you have an old version of the develop branch?

**Comment by b-g** [comment]
Hi Fabian, currently traveling ... sorry if I broke something! Can you roll back? Will then try to do it properly PR style. Best, B

Sent while in transit

**Comment by fabianmoronzirfas** [comment]
Well you did not merge yet. So no harm done. Also This is develop → master. So the number of commits could be right.  

What did you try to achieve? 

- [ ] Do a bug fix for `isNumber`? 
- [ ] Did you work directly in the develop branch?

**Comment by trych** [comment]
Yes, there is are two new commits in develop branch, which seem independent from this PR. Everything looks fine to me, there is just no mention in the changelog, I could add that later.

As we all tend to forget things again and again, I will go ahead and add this little check list to the Wiki. Feel free to add to this or to correct me:

## Checklist for creating a Pull Request

- [ ] Create your PR against the `develop` branch. The `master` branch is used for releases only.
- [ ] If you change any files in `src/includes`, make sure to bundle a new basil.js file before committing by running `npm run watch`.
- [ ] If you add or fix a feature, add it to `changelog.txt`
- [ ] If possible, add tests for new features or features with missing tests.

**Comment by b-g** [comment]
@fabianmoronzirfas Sorry for the my confusion. I mixed up branches ... all good now. 

@trych thanks for the checklist!

**Pull request closed without merging**
